### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by PallHaraldsson** [moble/Quaternionic.jl#26]
Hi, it's nice to see a good implementation, and I'm not even sure what it would look like, and I'll study your package more vs others.

I've been thinking of making my own, or starting with for complex, that I know better, only really thinking of the representation. I was thinking using fixed-point for the phase, 8-bits, might often be enough(?), and storing that way, not Cartesian. It's a small gain, but would be even better for higher-complex.

I don't really have an application for this, except I just know complex-valued neural networks are a thing, including higher-order up to sedenions, while none of them that popular (yet).

I see you have AbstractQuaternion, eventually it should be in some Base package all the implementations could share?

Do you have use for faster multiply of such matrices? I'm not sure my idea will be fast otherwise, only gaining from better memory-bandwidth.

**Comment by moble** [comment]
> Hi, it's nice to see a good implementation, and I'm not even sure what it would look like, and I'll study your package more vs others.

Thanks!

> I've been thinking of making my own, or starting with for complex, that I know better, only really thinking of the representation. I was thinking using fixed-point for the phase, 8-bits, might often be enough(?), and storing that way, not Cartesian. It's a small gain, but would be even better for higher-complex.
> [...]
> Do you have use for faster multiply of such matrices? I'm not sure my idea will be fast otherwise, only gaining from better memory-bandwidth.

I don't think I understand.  First, just to be clear, I don't use matrices here at all, except when transforming [to](https://github.com/moble/Quaternionic.jl/blob/a97d3e679baa265e2c20ef717fbc22f839735817/src/conversion.jl#L342) or [from](https://github.com/moble/Quaternionic.jl/blob/a97d3e679baa265e2c20ef717fbc22f839735817/src/conversion.jl#L302) a rotation matrix; everything else is done purely in terms of the 4 components of the quaternion — the "Cartesian" representation.

It's certainly be possible to use a pair of `Complex` numbers in standard Cartesian form to represent quaternion algebra, but any difference would probably optimize away — especially because `Complex` is actually [implemented in Julia](https://github.com/JuliaLang/julia/blob/37c0b0632771764f881184d68ecc3df318cfb32b/base/complex.jl) itself.  In fact, I can imagine that it would just make optimizations more difficult.  But you mention the phase, so do you mean representing a quaternion as two pairs of amplitude-and-phase (the "polar" representation)?  If so, you would still need to transform to the Cartesian representation for almost every operation, which would be very expensive.

> I see you have AbstractQuaternion, eventually it should be in some Base package all the implementations could share?

I suspect they wouldn't put it into Base; they seem happy to have external packages as de facto standards.  I was a bit surprised to see that [`Quaternions.jl`](https://github.com/JuliaGeometry/Quaternions.jl/) (which seems to be the most popular) didn't have such a thing.  But then, there aren't actually any subtypes in that package (unlike this one).  Anyway, people are free to use this `AbstractQuaternion` if they like it, or suggest improvements if they don't.

**Comment by PallHaraldsson** [comment]
>you would still need to transform to the Cartesian representation for almost every operation, which would be very expensive.

I know, why I mentioned big matrices, of e.g. Quaternions, i.e. every element of it is an element of them are such a "number" (meaning "4 components of the quaternion"). Then you're limited by memory bandwidth. I will not change the time-complexity, only the constant factor, and for multiplying it may be worth it. For addition it's already fast, will be a little slower. I still have some thought on that.

>I suspect they wouldn't put it into Base

Right, not in Julia Base (probably never), rather "some Base package", similar to I guess:

https://github.com/JuliaMath/AbstractFFTs.jl From memory this package was BaseFFT.

Most just use FFTW.jl (or other), implementing the above. There are lots of Base packages, that may be similar to what I had in mind (or not), e.g. PlotlyBase.jl and:

https://github.com/JuliaApproximation/ApproxFunBase.jl
